apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service
data:
  application.yaml: |-
    logging:
      level:
        org:
          springframework:
            web:
              servlet:
                DispatcherServlet: DEBUG