apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31003
  selector:
    appName: inventory
  sessionAffinity: ClientIP
