apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    frame: spring
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    appName: inventory
  sessionAffinity: ClientIP
