spring:
  application:
    name: spring-admin
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        service-labels:
          frame: spring
server:
  port: 8080
  servlet:
    context-path: /admin
