apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: spring-admin
build:
  artifacts:
    - image: open-ending.com/spring-admin
      jib:
        project: spring-admin
        args:
          - -DskipTests
  tagPolicy:
    gitCommit: {}
  local:
    {}
manifests:
  rawYaml:
    - k8s/**.yaml
    - ../k8s/privileges.yaml